# Generated by Django 2.2.2 on 2019-07-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MandiPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('market', models.CharField(max_length=100)),
                ('commodity', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('minP', models.CharField(max_length=100)),
                ('maxP', models.CharField(max_length=100)),
                ('modP', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
    ]
