# Generated by Django 2.2.2 on 2019-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Article',
        ),
    ]
