# Generated by Django 2.2.2 on 2019-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_news', '0002_auto_20190701_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
