# Generated by Django 2.0 on 2019-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_news', '0003_auto_20190701_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('summary', models.CharField(blank=True, default='', max_length=10000, null=True)),
            ],
        ),
    ]
